### ISSUE TITLE
jobError in sumstat$Z[qc$flip] = -1 * sumstat$Z[qc$flip] :

### ISSUE THREAD

**Issue by jameskozubek** [bogdanlab/fizi#3] opened 2021-01-20 04:14 UTC
Hello, I got this error. any advice?

(myenv) jim@bashful:/mnt/BIOINFX/fusion_twas-master$ Rscript FUSION.assoc_test.R --sumstats /mnt/BIOINFX/plm_automation/markers-data/markers-datasets/HS-IBD-5-3/imputed.cleaned.gwas1.sumstat.sumstat --weights ./WEIGHTS/GTEx.Colon_Sigmoid.pos --weights_dir ./WEIGHTS/ --ref_ld_chr ./LDREF/1000G.EUR. --chr 1 --out IBD-5-3-Colon_Sigmoid1

jobError in sumstat$Z[qc$flip] = -1 * sumstat$Z[qc$flip] :
  NAs are not allowed in subscripted assignments
Execution halted

**Comment by quattro** [comment] 2021-08-03 17:51
Hi @jameskozubek , can you provide a bit more information? Do you see any NAs in the `imputed.cleaned.gwas1.sumstat.sumstat` Z scores?

**Comment by quattro** [comment] 2021-08-03 17:52
Closing this as duplicate of #1

**Closed by quattro** 2021-08-03 17:52 UTC
Labels: bug
